### DISCUSSION TITLE
Installed on server with nginx reverse proxy but signup posts to localhost:4000

### DISCUSSION THREAD

**Discussion by kjgcoop** [omnivore-app/omnivore#4066] [Q&A]
I'm not sure if this is an Omnivore question or an nginx question. I installed Omnivore through Docker with all the default values except the passwords. I set up an nginx reverse proxy I swiped from https://stackoverflow.com/questions/16669773/nginx-reverse-proxy-to-backend-running-on-localhost so I can access it through the server's public IP on port 3000. 

When I submit the form to sign up, it redirects to localhost:4000. For lack of a better idea, I set up a second nginx proxy to expose port 4000. It doesn't seem to make a difference. 

I tried changing API_ENV to production, but I ran into different problems. It ultimately asked me for GCP details, and I gave up because I don't want to involve Google. 

Any help would be much appreciated!

**Comment by kjgcoop** [comment]
Having given it a minute, it occurs to me it's not an nginx issue. By the time Omnivore has written the signup form, it's already told it to be processed by localhost, so the request will never get to that server for nginx to process, it'll go straight to my laptop, which of course isn't in on the game. 

I tried replacing all instances of localhost in `docker-compose.yml`, but it's still posting to localhost. 

Any assistance would be much appreciated. Thank you!

**Comment by maa-x** [comment]
Can you share your nginx config and docker-compose.yml?

**Reply by kjgcoop** [reply]
Sure, thanks for your response.

The nginx config file:
```
server {
    listen 80; 
    server_name domain.somehost.com
    location / { 
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # https://unix.stackexchange.com/questions/290141/nginx-reverse-proxy-redirection
        :set proxy_redirect http://localhost:3000/ http://$remote_addr:3000/; 

    }   
}
```

All I changed in docker-compose.yml is swapping out `localhost` for the IP address:
```
version: '3'
services:
  postgres:
    image: "ankane/pgvector:v0.5.1"
    container_name: "omnivore-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=[password]
      - POSTGRES_DB=omnivore
      - PG_POOL_MAX=20
    healthcheck:
      test: "exit 0"
      interval: 2s
      timeout: 12s
      retries: 3
    expose:
      - 5432
    ports:
      - "5432:5432"

  migrate:
    build:
      context: .
      dockerfile: ./packages/db/Dockerfile
    container_name: "omnivore-migrate"
    command: '/bin/sh ./packages/db/setup.sh' # Also create a demo user with email: demo@omnivore.app, password: demo_password
    environment:
      - PGPASSWORD=[password]
      - POSTGRES_USER=postgres
      - PG_HOST=postgres
      - PG_PASSWORD=[password]
      - PG_DB=omnivore
    depends_on:
      postgres:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    container_name: "omnivore-api"
    ports:
      - "4000:8080"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 0.0.0.0 8080 || exit 1"]
      interval: 15s
      timeout: 90s
    environment:
      - API_ENV=local
      - PG_HOST=postgres
      - PG_USER=app_user
      - PG_PASSWORD=[password]
      - PG_DB=omnivore
      - PG_PORT=5432
      - PG_POOL_MAX=20
      - JAEGER_HOST=jaeger
      - IMAGE_PROXY_SECRET=[secret]
      - JWT_SECRET=some_secret
      - SSO_JWT_SECRET=[secret]
      - CLIENT_URL=http://[ip address]:3000
      - GATEWAY_URL=http://[ip address]:8080/api
      - CONTENT_FETCH_URL=http://content-fetch:8080/?token=[token]
    depends_on:
      migrate:
        condition: service_completed_successfully

  web:
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
      args:
        - APP_ENV=prod
        - BASE_URL=http://[ip address]:3000
        - SERVER_BASE_URL=http://[ip address]:4000
        - HIGHLIGHTS_BASE_URL=http://[ip address]:3000
    container_name: "omnivore-web"
    ports:
      - "3000:8080"
    environment:
      - NEXT_PUBLIC_APP_ENV=prod
      - NEXT_PUBLIC_BASE_URL=http://[ip address]:3000
      - NEXT_PUBLIC_SERVER_BASE_URL=http://[ip address]:4000
      - NEXT_PUBLIC_HIGHLIGHTS_BASE_URL=http://[ip address]:3000
    depends_on:
      api:
        condition: service_healthy

  content-fetch:
    build:
      context: .
      dockerfile: ./packages/content-fetch/Dockerfile
    container_name: "omnivore-content-fetch"
    ports:
      - "9090:8080"
    environment:
      - JWT_SECRET=[secret]
      - VERIFICATION_TOKEN=[token]
      - REST_BACKEND_ENDPOINT=http://api:8080/api
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
      api:
        condition: service_healthy

  redis:
    image: "redis:7.2.4"
    container_name: "omnivore-redis"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

```

Any insight would be much appreciated. Thank you!
