### ISSUE TITLE
[Enhancement] Define table borders for better readability

### ISSUE THREAD

**Issue by Bad3r** [omnivore-app/omnivore#1488]
Currently, tables are missing internal borders:

![](https://user-images.githubusercontent.com/25513724/204894549-3523e5f3-503c-464e-aa34-81e14e04af69.png)

For better readability, define table borders; for example:

  
**Before defining table border:**

![](https://logseq.abosen.top/assets/image_1638516056409_0.png)

**After defining table border:**

![](https://logseq.abosen.top/assets/image_1638516465090_0.png)

I recently fixed this same issue in Logseq using the following code snippet:

```css
/* Define Table Borders */
table.mytable {
    border-collapse: collapse;
    border-spacing: 0;
  }
  table.mytable td {
    text-align: center;
    vertical-align: middle;
    border-color: #D8DEE9;
    border-style: solid;
    border-width: 1px;
  }
  table.mytable th {
    text-align: center;
    vertical-align: middle;
    border-color: #D8DEE9;
    border-style: solid;
    border-width: 1px;
  }
```

The original code is from: https://logseq.abosen.top/#/page/logseq%E4%B8%AD%E5%A4%8D%E6%9D%82%E8%A1%A8%E6%A0%BC%E7%9A%84%E5%AE%9E%E7%8E%B0
